VENDOR_DB = {
    "2024-08-01": {"vendor_name": "Acme Corp", "services": ["Web hosting", "SSL certificates", "CDN"]},
    "2024-08-02": {"vendor_name": "TechSolutions Inc", "services": ["Software development", "QA testing"]},
    "2024-08-05": {"vendor_name": "CloudStream", "services": ["Cloud storage", "Data backup"]},
    "2024-08-06": {"vendor_name": "NetSecure", "services": ["Firewall", "Network monitoring"]},
    "2024-08-07": {"vendor_name": "DataMinds", "services": ["Data analytics", "Machine learning"]},
    "2024-08-08": {"vendor_name": "GlobalTech", "services": ["IT consulting", "System integration"]},
    "2024-08-09": {"vendor_name": "BrightSys", "services": ["Business intelligence", "ERP solutions"]},
    "2024-08-12": {"vendor_name": "FastConnect", "services": ["High-speed internet", "VoIP"]},
    "2024-08-13": {"vendor_name": "SecureIt", "services": ["Cybersecurity", "Data encryption"]},
    "2024-08-14": {"vendor_name": "GreenCloud", "services": ["SaaS solutions", "Cloud infrastructure"]},
    "2024-08-15": {"vendor_name": "CodeWorks", "services": ["Custom software", "API development"]},
    "2024-08-16": {"vendor_name": "SkyNet", "services": ["AI consulting", "Automation services"]},
    "2024-08-19": {"vendor_name": "InnovateIT", "services": ["Blockchain", "FinTech solutions"]},
    "2024-08-20": {"vendor_name": "BlueWave", "services": ["Managed IT services", "Helpdesk support"]},
    "2024-08-21": {"vendor_name": "OptiTech", "services": ["Optimization", "Scalability solutions"]},
    "2024-08-22": {"vendor_name": "NextGen", "services": ["DevOps", "Cloud architecture"]},
    "2024-08-23": {"vendor_name": "Visionary", "services": ["AR/VR development", "Immersive tech"]},
    "2024-08-26": {"vendor_name": "QuickFix", "services": ["Hardware repair", "Maintenance"]},
    "2024-08-27": {"vendor_name": "RedShield", "services": ["Network security", "Vulnerability scanning"]},
    "2024-08-28": {"vendor_name": "TechGenius", "services": ["AI-driven analytics", "Data science consulting"]},
    "2024-08-29": {"vendor_name": "UltraSoft", "services": ["Software licensing", "Product support"]},
    "2024-08-30": {"vendor_name": "Xcelerate", "services": ["Cloud migration", "Digital transformation"]},
}
